FROM ruby:3.0.2-alpine

RUN addgroup -g 1000 -S alip
RUN adduser -u 1000 -S alip -G alip

# <MSSQL>
# MSSQL_VERSION can be changed, by passing `--build-arg MSSQL_VERSION=<new version>` during docker build
ARG MSSQL_VERSION=17.5.2.1-1
ENV MSSQL_VERSION=${MSSQL_VERSION}

# Labels
LABEL maintainer="crobles@dbamastery.com"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.name="mssql-tools-alpine"
LABEL org.label-schema.description="mssql-tools image alternative with Alpine"
LABEL org.label-schema.url="http://dbamastery.com"

# Installing system utilities
RUN apk add --no-cache curl gnupg --virtual .build-dependencies -- && \
  # Adding custom MS repository for mssql-tools and msodbcsql
  curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_${MSSQL_VERSION}_amd64.apk && \
  curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_${MSSQL_VERSION}_amd64.apk && \
  # Verifying signature
  curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_${MSSQL_VERSION}_amd64.sig && \
  curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_${MSSQL_VERSION}_amd64.sig && \
  # Importing gpg key
  curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import - && \
  gpg --verify msodbcsql17_${MSSQL_VERSION}_amd64.sig msodbcsql17_${MSSQL_VERSION}_amd64.apk && \
  gpg --verify mssql-tools_${MSSQL_VERSION}_amd64.sig mssql-tools_${MSSQL_VERSION}_amd64.apk && \
  # Installing packages
  echo y | apk add --allow-untrusted msodbcsql17_${MSSQL_VERSION}_amd64.apk mssql-tools_${MSSQL_VERSION}_amd64.apk && \
  # Deleting packages
  apk del .build-dependencies && rm -f msodbcsql*.sig mssql-tools*.apk

# </MSSQL>

RUN apk add --update --virtual \
  runtime-deps \
  postgresql-client \
  build-base \
  libxml2-dev \
  libxslt-dev \
  nodejs \
  yarn \
  libffi-dev \
  readline \
  build-base \
  postgresql-dev \
  sqlite-dev \
  libc-dev \
  linux-headers \
  readline-dev \
  file \
  imagemagick \
  git \
  tzdata \
  && rm -rf /var/cache/apk/*

RUN apk add --no-cache --virtual \
  world freetds freetds-dev

RUN mkdir /gems
RUN mkdir /app
ENV BUNDLE_PATH /gems
RUN chown -Rf 1000:1000 /app/
RUN chown -Rf 1000:1000 /gems/

USER 1000:1000
WORKDIR /app
COPY . /app/

RUN yarn install
RUN bundle install

EXPOSE 3000